project:
  type: website
  output-dir: docs

website:
  title: "Man!What can I say!Mamba Out!"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

